name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@main

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pwgen:${{ github.run_number }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push username/pwgen:${{ github.run_number }}
